### ISSUE TITLE
What is BitpayAddress?

### ISSUE THREAD

**Issue by cshung1994** [bitcoincashjs/bchaddrjs#14]
I didn't find any resources about this type address.
I use bitpay and the address begin with '1' not 'C'
What kind of address is this?

**Comment by ealmansi** [comment]
hey @cshung1994,

This is an old address format introduced by BitPay at the time of the BCH fork. The goal was to prevent users from unintendedly sending BCH to BTC or vice versa. It has now been succeeded by the cash address format.
