### ISSUE TITLE
SLP address

### ISSUE THREAD

**Issue by Paulsky** [bitcoincashjs/bchaddrjs#16]
Hello,

Does this library also support validation of SLP addresses?

**Comment by Paulsky** [comment]
Maybe you could use some of the parts of a fork of this repository: https://github.com/simpleledger/bchaddrjs?

**Comment by ashwinichourasia** [comment]
Hi , is functions for converting slp address to legacy and vice versa is added in this Library ??

**Comment by ealmansi** [comment]
this library is in maintenance mode, only bug fixes and security upgrades will be added going forward
