### ISSUE TITLE
Is this library ready for use?

### ISSUE THREAD

**Issue by woodser** [bitcoincashjs/bchaddrjs#2]
Hi, I'm about to publicly release a tool which uses this library for Bitcoin Cash address translation.

Is this tool considered to be ready for use?  Any comments on tests, community review, general reliability or upcoming development?

Thanks!

**Comment by ealmansi** [comment]
Hi @woodser,

All functionality described in the [docs](https://cdn.rawgit.com/bitcoincashjs/bchaddrjs/master/jsdoc/module-bchaddr.html) and displayed in the [examples](https://github.com/bitcoincashjs/bchaddrjs#code-examples) section is ready to be used. There is a comprehensive [test suite](https://github.com/bitcoincashjs/bchaddrjs/blob/master/test/bchaddr.js) with full coverage. This is a new library, so use with caution; peer review on the code or feature requests for the API are very welcome.

The library will be kept updated upon future Bitcoin Cash address translation requirements, although none have been announced yet for the near to medium term.

**Comment by woodser** [comment]
Ok.  Thank you @ealmansi!

**Comment by ealmansi** [comment]
NP. Share your new tool here if you'd like. Your project can be added to a 'Projects using BchAddr.js' list, too.

**Comment by woodser** [comment]
cryptostorage.com :)  Shhh... announcing very soon.  Tomorrow if I can get this working.

I'm now trying to get UInt8Array.from() and UInt8Array.of() within bchaddr.js working for IE11 if you have any suggestions.  Otherwise the site runs on IE11.

**Comment by ealmansi** [comment]
Your app looks sweet; looking forward to the announcement.

Regarding Uint8Array.from() and .of() you can:
i) Manually add the polyfills suggested by Mozilla ([from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from#Polyfill), [of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/of#Polyfill)).
ii) Use the [TypedArray](https://github.com/inexorabletash/polyfill/blob/master/typedarray.js) polyfill from this project: https://github.com/inexorabletash/polyfill

**Comment by woodser** [comment]
Sweet!  I was able to get it working with the second link you sent.  Thanks for your help!
