### ISSUE TITLE
decodeAddress (and its variations) should be public

### ISSUE THREAD

**Issue by ejose19** [bitcoincashjs/bchaddrjs#21]
Doing so will make many operations way easier, for example in order to get all the information for an address, one needs to run `isValidAddress` first (or wrap all operations in try-catch), and then call all `detectAddress` methods individually (which are already using `decodeAddress` as source);

Also, there may be cases where one wants to check the output of `cashaddr` decode directly (for example, accessing prefix property which do includes `bchreg` and `detectNetwork` treats it as `testnet`)

**Comment by ealmansi** [comment]
the lower level library [cashaddrj](https://www.npmjs.com/package/cashaddrjs) is better suited for that use case
