### ISSUE TITLE
Package not actually in bower

### ISSUE THREAD

**Issue by flotwig** [bitcoincashjs/bchaddrjs#4]
If you try to install this package via bower as indicated in the README, you get these results:

```
bower i --save bchaddrjs
bower                        ENOTFOUND Package bchaddrjs not found
```

You can also confirm this by searching the packages at https://bower.io/.

In the mean time, I have the package installed and running next to my other bower modules with:
```
bower i --save https://github.com/bitcoincashjs/bchaddrjs.git
```

**Comment by ealmansi** [comment]
Thx! Will fix this ASAP
