### ISSUE TITLE
BCH address is invalid

### ISSUE THREAD

**Issue by Dmatafonov** [bitcoincashjs/bchaddrjs#5]
Was searching web for js lib to verify bch address, and found you lib.

Cant get my coinomi wallet address to validate, lib shows that it invalid:

`qqvek95wvh6gxg5aeyv6u4huxtwxmpm575rsvn40yz`

```
bchaddr.isMainnetAddress('qqvek95wvh6gxg5aeyv6u4huxtwxmpm575rsvn40yz')
```

And all other functions (cashAddress, etc)

What is wrong with that address?

**Comment by Dmatafonov** [comment]
![image](https://user-images.githubusercontent.com/8863854/36694161-26869d10-1b46-11e8-9c8c-9f2355592521.png)

**Comment by Dmatafonov** [comment]
Took some random addresses from https://blockchair.com/bitcoin-cash/transaction/d7c017a4bc147504da8fdf60364d2987debda5c19b14567f41e812939baf486d

All are invalid. Something definitely wrong in what Im doing.

```
bchaddr.isCashAddress('pq9wu6klkr67ww6fz2r8v4e6pcenvgqmkgy677vszd')
```

**Comment by ealmansi** [comment]
Hi @Dmatafonov ,

I've just tested the two examples you've provided and they seem to be working for me:

```
> bchaddr.isMainnetAddress('qqvek95wvh6gxg5aeyv6u4huxtwxmpm575rsvn40yz')
true
> bchaddr.isCashAddress('pq9wu6klkr67ww6fz2r8v4e6pcenvgqmkgy677vszd')
true
```

This is most likely an issue with your node version. Could you please share the output of the following command on your system?

```
npm --version
node --version
```

**Comment by Dmatafonov** [comment]
I'm doing it in the browser, not in the node. I need a client side protection from wrong inputs.

**Comment by ealmansi** [comment]
Could you share what browser and version you're testing this on?

**Comment by Dmatafonov** [comment]
Here is what I tried
```
<script src="https://cdn.rawgit.com/bitcoincashjs/bchaddrjs/master/dist/bchaddrjs-0.2.1.min.js"></script>
```

And then
```
bchaddr.isMainnetAddress('qqvek95wvh6gxg5aeyv6u4huxtwxmpm575rsvn40yz')
```

![image](https://user-images.githubusercontent.com/8863854/36838176-22242d66-1d47-11e8-9280-6d7c437f4d3e.png)



Browser chrome 64.0

**Comment by Dmatafonov** [comment]
@ealmansi any ideas how to fix?

**Comment by Dmatafonov** [comment]
@ealmansi any update on this?
